### ISSUE TITLE
PHP SAM is missed / verification 

### ISSUE THREAD

**Issue by pewpew4141414** [Newcomer1989/TSN-Ranksystem#404]
after the new update came out i started getting this error everytime i run the bot and the verification doesn't even work. it doesn't show up my client i tried to reset my channel id and made a new one but still was nothing this is the errors.

![screenshot_6](https://user-images.githubusercontent.com/36430813/36130770-3e42ebc2-1077-11e8-88ce-9490921bc176.png)

**Comment by Shad86** [comment]
Hello,

Please download the original sources and overwrite it on your machine.
https://ts-n.net/downloads/ranksystem_1.2.4.zip

Take note, that you do not overwrite the other/dbconfig.php and the other/phpcommand.php.
Also you should not upload the install.php on your webspace.
So exclude this 3 files from uploading.

**Comment by Shad86** [comment]
Fixed, answered on teamspeak that he solved his issue.

**Comment by mamayer** [comment]
I had the same issue after auto-update. May me a more common bug than just once.

**Comment by Lukas9914** [comment]
Same here. Isn't working after reinstall with the zip. Same Problem with PHP-SAM

**Comment by Newcomer1989** [comment]
> Same here. Isn't working after reinstall with the zip. Same Problem with PHP-SAM

You are sure, it is still the same error? You took it really from https://ts-n.net/downloads/ranksystem_1.2.4.zip ?

It should be working, when you done it correct. Please check you take an actual download and you are correctly overwriting the files on your webspace.

**Comment by Lukas9914** [comment]
OK, sorry my fault. Now everything is fine.
Thx
