### ISSUE TITLE
TeaSpeak Support

### ISSUE THREAD

**Issue by Coolguy3289** [Newcomer1989/TSN-Ranksystem#563]
I've installed the bot on a server (Specs below), and when I start the bot it will connect and start bot functions, but it just continuously loops the jobs without writing anything to the database, so all of the initial output (ServerGroup Icon Downloads, Clients connected being added to DB, etc) will just constantly repeat. The big issue, is that I'm getting NO error messages in the logs. Log file below.
System Specs: 
```
Ubuntu 16.04
TeaSpeak 1.2.31-beta-2
php-fpm 7.2
```
Error Logs:
```
2018-12-10 08:35:46.431721   DEBUG     Successful login attempt to the webinterface from IP 10.0.0.250.
2018-12-10 02:37:24.682925   INFO      ###################################################################
2018-12-10 02:37:24.696784   INFO
2018-12-10 02:37:24.696831   INFO      ###################################################################
2018-12-10 02:37:24.696872   INFO      Initialize Bot...
2018-12-10 02:37:24.750692   DEBUG     Running on OS: Linux 4.4.0-131-generic
2018-12-10 02:37:24.750780   DEBUG     Using PHP Version: 7.2.13-1+ubuntu16.04.1+deb.sury.org+1
2018-12-10 02:37:24.750838   DEBUG     Database Version: 5.5.5-10.2.19-MariaDB-10.2.19+maria~xenial
2018-12-10 02:37:24.750881   INFO      Check Ranksystem database for updates...
2018-12-10 02:37:24.750925   INFO        No newer version detected; Database check finished.
2018-12-10 02:37:24.751524   INFO        Check files permissions...
2018-12-10 02:37:24.758075   INFO        Check files permissions [done]
2018-12-10 02:37:24.758136   INFO      Check Ranksystem database for updates [done]
2018-12-10 02:37:24.758179   INFO      Check Ranksystem files for updates...
2018-12-10 02:37:24.758224   INFO      Check Ranksystem files for updates [done]
2018-12-10 02:37:24.758265   INFO      Ranksystem Version: 1.2.11
2018-12-10 02:37:24.758305   INFO      Loading addons...
2018-12-10 02:37:24.768274   INFO        Addon: 'assign_groups' [OFF]
2018-12-10 02:37:24.768340   INFO      Loading addons [done]
2018-12-10 02:37:24.768386   INFO      Connect to TS3 Server (Address: "10.0.0.34" Voice-Port: "9987" Query-Port: "10101" SSH: "0").
2018-12-10 02:37:26.001703   INFO      Connection to TS3 Server established.
2018-12-10 02:37:26.002302   INFO        TS3 Server version: 1.2.30-beta on Linux [Build: 1543280463 from 2018-11-26 20:01:03]
2018-12-10 02:37:26.002351   INFO          Select virtual server...
2018-12-10 02:37:26.002398   WARNING         Your TS3 server is outdated, please update it!
2018-12-10 02:37:26.512712   INFO          Select virtual server [done]
2018-12-10 02:37:26.715433   NOTICE      No channel defined where the Ranksystem Bot should be entered.
2018-12-10 02:37:26.715510   INFO      Config check started...
2018-12-10 02:37:26.716190   INFO      Config check [done]
2018-12-10 02:37:26.716249   INFO      Bot starts now his work!
2018-12-10 02:37:30.181102   NOTICE    Much time gone since last scan.. reset time difference to zero.
2018-12-10 02:37:30.181244   INFO      User 'Cherry' (unique Client-ID: XwqKyeZwBpo3+AqpQh5yeVuTKO0=; Client-database-ID 899) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181311   INFO      User 'Coolguy3289' (unique Client-ID: PjR6Xyw3IEzWSlgOJgAEv3rxQm0=; Client-database-ID 25) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181374   INFO      User 'JoroxTheAncient' (unique Client-ID: H/wrA4IOfEisQO86UdIqctjcBgQ=; Client-database-ID 3) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181435   INFO      User 'Kei Shin' (unique Client-ID: MHlgePC/7WCDJLwsAsGuy5RKywE=; Client-database-ID 7) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181495   INFO      User 'Kirinae Windstalker' (unique Client-ID: XpA6OX9ncqHAfYR/0Kf0kNV7LHM=; Client-database-ID 12) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181555   INFO      User 'DOOMGUY' (unique Client-ID: lfgX3icLSmFcfrEG8/9ZK59oSVM=; Client-database-ID 30) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181616   INFO      User 'Parker' (unique Client-ID: 4CJ8GdwGSOqywCMXNuzMw+ENheU=; Client-database-ID 11) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181675   INFO      User 'Sigaultio' (unique Client-ID: VkM0TnFI2hDY6oxSGoc66XOU6e8=; Client-database-ID 8) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181735   INFO      User 'Pleb' (unique Client-ID: TF5RXlXNaS2mgvGVXBGg6gExzWQ=; Client-database-ID 763) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181794   INFO      User 'TestBot' (unique Client-ID: lVCeNgV9mQrbXBwgHrTy7NM5bcQ=; Client-database-ID 29) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181864   INFO      User 'Wonko the Sane' (unique Client-ID: gvIHLEr8bje3V6v9hb9FMyTXpIk=; Client-database-ID 9) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181924   INFO      User 'Broken_Kittey' (unique Client-ID: keFjC+7U1qt7R2wopbbVU8aP68g=; Client-database-ID 4) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.181983   INFO      User 'Wanko' (unique Client-ID: music#m5AlLkb0ETwwCga; Client-database-ID 1421) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.182041   INFO      User 'Autumn' (unique Client-ID: VwF6mDUg6Xyxv0H6PhLZXMDOXrI=; Client-database-ID 22) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.182100   INFO      User 'RankMaster' (unique Client-ID: serveradmin; Client-database-ID 1) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.182164   INFO      User 'TestBot2' (unique Client-ID: XaBcxAen0PhCRlz8ClgVQgoyXJI=; Client-database-ID 1422) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:30.757107   INFO      Download avatar: /avatar_dfnpenhdaddnmphgglbdioeiiogfmlcbbjhndifa
2018-12-10 02:37:30.963126   INFO      Download avatar: /avatar_fgeddeeohbeinkbaniokimfcbkihdkojhdjeojop
2018-12-10 02:37:31.167765   INFO      Download avatar: /avatar_fpakikmjoghaagjkdhpiakkjecbohchjfljdcion
2018-12-10 02:37:31.379185   INFO      Download avatar: /avatar_jbobgdaloonengklhlehgmcikflgnffdmgipolmi
2018-12-10 02:37:31.582299   INFO      Download avatar: /avatar_oacchmbjnmageioklcmacdbhdgommmmdobanifof
2018-12-10 02:37:31.582462   NOTICE    Scanning for clients to delete...
2018-12-10 02:37:31.582510   INFO        Get TS3 Clientlist...
2018-12-10 02:37:31.748314   DEBUG         Got TS3 Clientlist 200 of 699 Clients.
2018-12-10 02:37:32.111481   DEBUG         Got TS3 Clientlist 400 of 699 Clients.
2018-12-10 02:37:32.484068   DEBUG         Got TS3 Clientlist 600 of 699 Clients.
2018-12-10 02:37:32.766012   DEBUG         Got TS3 Clientlist 699 of 699 Clients.
2018-12-10 02:37:32.766115   INFO        Get TS3 Clientlist [DONE]
2018-12-10 02:37:32.766424   NOTICE      Clients found in the TeamSpeak database: 0 (of 699)
2018-12-10 02:37:32.766469   NOTICE      Clients in the Ranksystem database: 0
2018-12-10 02:37:32.766511   NOTICE      There was nothing to delete...
2018-12-10 02:37:32.766572   NOTICE    Check for cleaning database done. All unnecessary stuff was deleted.
2018-12-10 02:37:34.450312   INFO      Download new ServerIcon
2018-12-10 02:37:34.673956   INFO      Download new ServerGroupIcon for group 'Server Admin' with ID: 103
2018-12-10 02:37:34.885830   INFO      Download new ServerGroupIcon for group 'ROB' with ID: 108
2018-12-10 02:37:35.091587   INFO      Download new ServerGroupIcon for group 'Head Admin' with ID: 109
2018-12-10 02:37:35.294191   INFO      Download new ServerGroupIcon for group 'Admin' with ID: 106
2018-12-10 02:37:35.496761   INFO      Download new ServerGroupIcon for group 'Head OP' with ID: 110
2018-12-10 02:37:35.699615   INFO      Download new ServerGroupIcon for group 'OP' with ID: 111
2018-12-10 02:37:35.906256   INFO      Download new ServerGroupIcon for group 'NUGaIS' with ID: 114
2018-12-10 02:37:36.113250   INFO      Download new ServerGroupIcon for group 'Community Owner' with ID: 118
2018-12-10 02:37:36.316284   INFO      Download new ServerGroupIcon for group 'Network Staff' with ID: 149
2018-12-10 02:37:36.519202   INFO      Download new ServerGroupIcon for group 'My Dude My Guy' with ID: 117
2018-12-10 02:37:37.110696   INFO      User 'Cherry' (unique Client-ID: XwqKyeZwBpo3+AqpQh5yeVuTKO0=; Client-database-ID 899) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.110809   INFO      User 'Coolguy3289' (unique Client-ID: PjR6Xyw3IEzWSlgOJgAEv3rxQm0=; Client-database-ID 25) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.110875   INFO      User 'JoroxTheAncient' (unique Client-ID: H/wrA4IOfEisQO86UdIqctjcBgQ=; Client-database-ID 3) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.110937   INFO      User 'Kei Shin' (unique Client-ID: MHlgePC/7WCDJLwsAsGuy5RKywE=; Client-database-ID 7) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111008   INFO      User 'Kirinae Windstalker' (unique Client-ID: XpA6OX9ncqHAfYR/0Kf0kNV7LHM=; Client-database-ID 12) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111069   INFO      User 'DOOMGUY' (unique Client-ID: lfgX3icLSmFcfrEG8/9ZK59oSVM=; Client-database-ID 30) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111129   INFO      User 'Parker' (unique Client-ID: 4CJ8GdwGSOqywCMXNuzMw+ENheU=; Client-database-ID 11) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111190   INFO      User 'Sigaultio' (unique Client-ID: VkM0TnFI2hDY6oxSGoc66XOU6e8=; Client-database-ID 8) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111251   INFO      User 'Pleb' (unique Client-ID: TF5RXlXNaS2mgvGVXBGg6gExzWQ=; Client-database-ID 763) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111311   INFO      User 'TestBot' (unique Client-ID: lVCeNgV9mQrbXBwgHrTy7NM5bcQ=; Client-database-ID 29) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111371   INFO      User 'Wonko the Sane' (unique Client-ID: gvIHLEr8bje3V6v9hb9FMyTXpIk=; Client-database-ID 9) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111430   INFO      User 'Broken_Kittey' (unique Client-ID: keFjC+7U1qt7R2wopbbVU8aP68g=; Client-database-ID 4) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111490   INFO      User 'Wanko' (unique Client-ID: music#m5AlLkb0ETwwCga; Client-database-ID 1421) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111550   INFO      User 'Autumn' (unique Client-ID: VwF6mDUg6Xyxv0H6PhLZXMDOXrI=; Client-database-ID 22) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111609   INFO      User 'RankMaster' (unique Client-ID: serveradmin; Client-database-ID 1) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.111673   INFO      User 'TestBot2' (unique Client-ID: XaBcxAen0PhCRlz8ClgVQgoyXJI=; Client-database-ID 1422) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:37.313709   NOTICE    Scanning for clients to delete...
2018-12-10 02:37:37.313791   INFO        Get TS3 Clientlist...
2018-12-10 02:37:37.471454   DEBUG         Got TS3 Clientlist 200 of 699 Clients.
2018-12-10 02:37:37.829986   DEBUG         Got TS3 Clientlist 400 of 699 Clients.
2018-12-10 02:37:38.188716   DEBUG         Got TS3 Clientlist 600 of 699 Clients.
2018-12-10 02:37:38.469428   DEBUG         Got TS3 Clientlist 699 of 699 Clients.
2018-12-10 02:37:38.469520   INFO        Get TS3 Clientlist [DONE]
2018-12-10 02:37:38.470060   NOTICE      Clients found in the TeamSpeak database: 0 (of 699)
2018-12-10 02:37:38.470109   NOTICE      Clients in the Ranksystem database: 0
2018-12-10 02:37:38.470152   NOTICE      There was nothing to delete...
2018-12-10 02:37:38.470201   NOTICE    Check for cleaning database done. All unnecessary stuff was deleted.
2018-12-10 02:37:39.613950   INFO      Download new ServerIcon
2018-12-10 02:37:39.824729   INFO      Download new ServerGroupIcon for group 'Server Admin' with ID: 103
2018-12-10 02:37:40.027057   INFO      Download new ServerGroupIcon for group 'ROB' with ID: 108
2018-12-10 02:37:40.229528   INFO      Download new ServerGroupIcon for group 'Head Admin' with ID: 109
2018-12-10 02:37:40.431990   INFO      Download new ServerGroupIcon for group 'Admin' with ID: 106
2018-12-10 02:37:40.634478   INFO      Download new ServerGroupIcon for group 'Head OP' with ID: 110
2018-12-10 02:37:40.836885   INFO      Download new ServerGroupIcon for group 'OP' with ID: 111
2018-12-10 02:37:41.039540   INFO      Download new ServerGroupIcon for group 'NUGaIS' with ID: 114
2018-12-10 02:37:41.242073   INFO      Download new ServerGroupIcon for group 'Community Owner' with ID: 118
2018-12-10 02:37:41.444404   INFO      Download new ServerGroupIcon for group 'Network Staff' with ID: 149
2018-12-10 02:37:41.646977   INFO      Download new ServerGroupIcon for group 'My Dude My Guy' with ID: 117
2018-12-10 02:37:42.149110   INFO      User 'Cherry' (unique Client-ID: XwqKyeZwBpo3+AqpQh5yeVuTKO0=; Client-database-ID 899) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:42.149236   INFO      User 'Coolguy3289' (unique Client-ID: PjR6Xyw3IEzWSlgOJgAEv3rxQm0=; Client-database-ID 25) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:42.149309   INFO      User 'JoroxTheAncient' (unique Client-ID: H/wrA4IOfEisQO86UdIqctjcBgQ=; Client-database-ID 3) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:42.149372   INFO      User 'Kei Shin' (unique Client-ID: MHlgePC/7WCDJLwsAsGuy5RKywE=; Client-database-ID 7) is unknown -> added to the Ranksystem now.
2018-12-10 02:37:42.149443   INFO      User 'Kirinae Windstalker' (unique Client-ID: XpA6OX9ncqHAfYR/0Kf0kNV7LHM=; Client-database-ID 12) is unknown -> added to the Ranksystem now.
```
etc. etc. The above log file goes on and on. Any ideas? I've not seen a single error.

**Comment by Shad86** [comment]
TeaSpeak is not supported atm

**Comment by Coolguy3289** [comment]
For the most part, the query should act the same, Are you aware of the specifics that cause this issue?

**Comment by Shad86** [comment]
The developer has already taken a look at this, but due to a lack of documentation he has not pursued it any further.

As you yourself said "For the most part, the query should act the same" - as long as no 100% support is promised by the developer, I won't spend any time dealing with an undocumented alpha software.

**Comment by Shad86** [comment]
See also here -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/529

**Comment by Coolguy3289** [comment]
I've posted asking for documentation.

**Comment by Coolguy3289** [comment]
Documentation is here, dunno where you were looking:
https://github.com/TeaSpeak/TeaSpeak/tree/master/default_files/commanddocs
https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/ServerQueryNotify.md
https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/Music bot query interface.md

**Comment by Shad86** [comment]
Okay, then still the dev have to look into this.

Do you use .svg icons? as i know they are currently not supported.

**Comment by Newcomer1989** [comment]
Thx for posting the documentations. We need to have a look on it. After we need to check each command is exactly working as TeamSpeak does it. If yes, there must be a bug in TeaSpeak. If no, we need to have a look to develope a support for TeaSpeak.
This will need a while. We will let you informed here.

**Comment by Bluscream** [comment]
I am also waiting for this. You can get help/ask questions directly at https://github.com/TeaSpeak/TeaSpeak/issues/ or just join the support TeaSpeak ts3server://ts.teaspeak.de

**Comment by Bluscream** [comment]
Okay so after some discussion with @Chazotu and @Shad86 we think the problem might be the fact that the `count` parameter of the `clientdblist -count` response is probably the cause for this because on teamspeak it's always the first element and in teaspeak it's the last element of the first "client" from the db. (see screenshot)

![image](https://user-images.githubusercontent.com/3318223/51401132-55a64280-1b4a-11e9-972a-174b6df17651.png)

**Comment by Coolguy3289** [comment]
Just updated our TeaSpeak server. Will test this and confirm functionality.

**Comment by Coolguy3289** [comment]
Still having the same issue.

**Comment by Newcomer1989** [comment]
Are you using a test-system for this? Are user **external** online on your TeaSpeak server? Or only local user?

We have fixed special constellations inside the current beta. You can check this inside the changelog.
https://ts-ranksystem.com/#changelog

Perhaps you would like to switch on your test-system to the beta channel (Webinterface -> Other -> Update-Channel) and check it with this version.

**Comment by Coolguy3289** [comment]
We are using our production Teaspeak server for this. Users are connecting from the external network. I will try using the beta channel of the system to see if that works and will report back.

**Comment by almir101** [comment]
Do you still have same issue? I may help you fix this problem. Contact me on ts.life2game.info
nickname i-OniK.

**Comment by Newcomer1989** [comment]
Please try the current beta version. We have fixed one issue with TeaSpeak with this #630 

When you still have problems, let me know it.

**Comment by Coolguy3289** [comment]
I have switched to the Beta branch, and am still having the same issue of nothing being written into the database. Also, when I go the stats page to manually verify myself, it doesn't detect anyone in the channel (even though I'm there).

**Comment by Newcomer1989** [comment]
Which version exactly runs on your system?

**Comment by Coolguy3289** [comment]
Rankbot version: 1.3.3

**Comment by Newcomer1989** [comment]
Can you send us here the dump file out of /logs/temp_sql_dump.sql? Thx in advance!

You need to start the Ranksystem with Debug-Mode to get this file -> Webinterface -> Other -> Log-Level -> 6 - Debug

**Comment by Coolguy3289** [comment]
[temp_sql_dump.sql.txt](https://github.com/Newcomer1989/TSN-Ranksystem/files/3495186/temp_sql_dump.sql.txt)

**Comment by Newcomer1989** [comment]
It is a longer time ago, this issue were posted. I guess the most problems with TeaSpeak are solved.

If there are still problems, feel free to open a new issue.
